#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libaccounts-glib
Version  : 1.25
Release  : 1
URL      : https://gitlab.com/accounts-sso/libaccounts-glib/-/archive/1.25/libaccounts-glib-1.25.tar.gz
Source0  : https://gitlab.com/accounts-sso/libaccounts-glib/-/archive/1.25/libaccounts-glib-1.25.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: libaccounts-glib-bin = %{version}-%{release}
Requires: libaccounts-glib-data = %{version}-%{release}
Requires: libaccounts-glib-lib = %{version}-%{release}
Requires: libaccounts-glib-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : glib-dev
BuildRequires : gtk-doc
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-introspection-1.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : sqlite-autoconf-dev
BuildRequires : vala

%description
Accounts management library for GLib applications
=================================================

%package bin
Summary: bin components for the libaccounts-glib package.
Group: Binaries
Requires: libaccounts-glib-data = %{version}-%{release}
Requires: libaccounts-glib-license = %{version}-%{release}

%description bin
bin components for the libaccounts-glib package.


%package data
Summary: data components for the libaccounts-glib package.
Group: Data

%description data
data components for the libaccounts-glib package.


%package dev
Summary: dev components for the libaccounts-glib package.
Group: Development
Requires: libaccounts-glib-lib = %{version}-%{release}
Requires: libaccounts-glib-bin = %{version}-%{release}
Requires: libaccounts-glib-data = %{version}-%{release}
Provides: libaccounts-glib-devel = %{version}-%{release}
Requires: libaccounts-glib = %{version}-%{release}

%description dev
dev components for the libaccounts-glib package.


%package doc
Summary: doc components for the libaccounts-glib package.
Group: Documentation

%description doc
doc components for the libaccounts-glib package.


%package lib
Summary: lib components for the libaccounts-glib package.
Group: Libraries
Requires: libaccounts-glib-data = %{version}-%{release}
Requires: libaccounts-glib-license = %{version}-%{release}

%description lib
lib components for the libaccounts-glib package.


%package license
Summary: license components for the libaccounts-glib package.
Group: Default

%description license
license components for the libaccounts-glib package.


%prep
%setup -q -n libaccounts-glib-1.25
cd %{_builddir}/libaccounts-glib-1.25

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1634567941
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dpy-overrides-dir="/usr"  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libaccounts-glib
cp %{_builddir}/libaccounts-glib-1.25/COPYING %{buildroot}/usr/share/package-licenses/libaccounts-glib/4df5d4b947cf4e63e675729dd3f168ba844483c7
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
/usr/Accounts.py

%files bin
%defattr(-,root,root,-)
/usr/bin/ag-backup
/usr/bin/ag-tool

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Accounts-1.0.typelib
/usr/share/dbus-1/interfaces/com.google.code.AccountsSSO.Accounts.Manager.xml
/usr/share/gettext/its/accounts-application.its
/usr/share/gettext/its/accounts-application.loc
/usr/share/gettext/its/accounts-provider.its
/usr/share/gettext/its/accounts-provider.loc
/usr/share/gettext/its/accounts-service-type.its
/usr/share/gettext/its/accounts-service-type.loc
/usr/share/gettext/its/accounts-service.its
/usr/share/gettext/its/accounts-service.loc
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/libaccounts-glib.deps
/usr/share/vala/vapi/libaccounts-glib.vapi
/usr/share/xml/accounts/schema/dtd/accounts-application.dtd
/usr/share/xml/accounts/schema/dtd/accounts-provider.dtd
/usr/share/xml/accounts/schema/dtd/accounts-service-type.dtd
/usr/share/xml/accounts/schema/dtd/accounts-service.dtd

%files dev
%defattr(-,root,root,-)
/usr/include/libaccounts-glib/accounts-glib.h
/usr/include/libaccounts-glib/ag-account-service.h
/usr/include/libaccounts-glib/ag-account.h
/usr/include/libaccounts-glib/ag-application.h
/usr/include/libaccounts-glib/ag-auth-data.h
/usr/include/libaccounts-glib/ag-autocleanups.h
/usr/include/libaccounts-glib/ag-errors.h
/usr/include/libaccounts-glib/ag-manager.h
/usr/include/libaccounts-glib/ag-provider.h
/usr/include/libaccounts-glib/ag-service-type.h
/usr/include/libaccounts-glib/ag-service.h
/usr/include/libaccounts-glib/ag-types.h
/usr/include/libaccounts-glib/libaccounts-glib.h
/usr/lib64/libaccounts-glib.so
/usr/lib64/pkgconfig/libaccounts-glib.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/libaccounts-glib/AgAccount.html
/usr/share/gtk-doc/html/libaccounts-glib/AgAccountService.html
/usr/share/gtk-doc/html/libaccounts-glib/AgManager.html
/usr/share/gtk-doc/html/libaccounts-glib/account-management.html
/usr/share/gtk-doc/html/libaccounts-glib/ag-backup.html
/usr/share/gtk-doc/html/libaccounts-glib/ag-tool.html
/usr/share/gtk-doc/html/libaccounts-glib/annotation-glossary.html
/usr/share/gtk-doc/html/libaccounts-glib/api-index-1-1.html
/usr/share/gtk-doc/html/libaccounts-glib/api-index-1-14.html
/usr/share/gtk-doc/html/libaccounts-glib/api-index-1-2.html
/usr/share/gtk-doc/html/libaccounts-glib/api-index-1-25.html
/usr/share/gtk-doc/html/libaccounts-glib/api-index-1-4.html
/usr/share/gtk-doc/html/libaccounts-glib/api-index-1-5.html
/usr/share/gtk-doc/html/libaccounts-glib/api-index-deprecated.html
/usr/share/gtk-doc/html/libaccounts-glib/api-index-full.html
/usr/share/gtk-doc/html/libaccounts-glib/appendices.html
/usr/share/gtk-doc/html/libaccounts-glib/gettext-xml-files.html
/usr/share/gtk-doc/html/libaccounts-glib/glossary.html
/usr/share/gtk-doc/html/libaccounts-glib/home.png
/usr/share/gtk-doc/html/libaccounts-glib/index.html
/usr/share/gtk-doc/html/libaccounts-glib/left-insensitive.png
/usr/share/gtk-doc/html/libaccounts-glib/left.png
/usr/share/gtk-doc/html/libaccounts-glib/libaccounts-compiling.html
/usr/share/gtk-doc/html/libaccounts-glib/libaccounts-glib-ag-application.html
/usr/share/gtk-doc/html/libaccounts-glib/libaccounts-glib-ag-auth-data.html
/usr/share/gtk-doc/html/libaccounts-glib/libaccounts-glib-ag-provider.html
/usr/share/gtk-doc/html/libaccounts-glib/libaccounts-glib-ag-service-type.html
/usr/share/gtk-doc/html/libaccounts-glib/libaccounts-glib-ag-service.html
/usr/share/gtk-doc/html/libaccounts-glib/libaccounts-glib-objects.html
/usr/share/gtk-doc/html/libaccounts-glib/libaccounts-glib-overview.html
/usr/share/gtk-doc/html/libaccounts-glib/libaccounts-glib-tools.html
/usr/share/gtk-doc/html/libaccounts-glib/libaccounts-glib.devhelp2
/usr/share/gtk-doc/html/libaccounts-glib/libaccounts-overview.html
/usr/share/gtk-doc/html/libaccounts-glib/libaccounts-running.html
/usr/share/gtk-doc/html/libaccounts-glib/provider-file-format.html
/usr/share/gtk-doc/html/libaccounts-glib/right-insensitive.png
/usr/share/gtk-doc/html/libaccounts-glib/right.png
/usr/share/gtk-doc/html/libaccounts-glib/service-file-format.html
/usr/share/gtk-doc/html/libaccounts-glib/service-type-file-format.html
/usr/share/gtk-doc/html/libaccounts-glib/style.css
/usr/share/gtk-doc/html/libaccounts-glib/up-insensitive.png
/usr/share/gtk-doc/html/libaccounts-glib/up.png
/usr/share/gtk-doc/html/libaccounts-glib/validating-xml-files.html
/usr/share/gtk-doc/html/libaccounts-glib/xml-file-formats.html
/usr/share/gtk-doc/html/libaccounts-glib/xml-files.html

%files lib
%defattr(-,root,root,-)
/usr/lib64/libaccounts-glib.so.0
/usr/lib64/libaccounts-glib.so.1.25

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libaccounts-glib/4df5d4b947cf4e63e675729dd3f168ba844483c7
